# Write your MySQL query statement below
SELECT E.EMPLOYEE_ID 
FROM EMPLOYEES E LEFT JOIN SALARIES S
ON E.EMPLOYEE_ID = S.EMPLOYEE_ID
WHERE S.SALARY IS NULL
UNION
(SELECT S.EMPLOYEE_ID 
FROM SALARIES S LEFT JOIN EMPLOYEES E
ON S.EMPLOYEE_ID = E.EMPLOYEE_ID
WHERE E.NAME IS NULL)
ORDER BY EMPLOYEE_ID